adafruit/circup

circup.py
This very quick and simple change adds a feature requested by @makermelissa:
The update command now takes an `--all` flag which circumvents the confirmation checks for each out-of-date module and just updates everything automatically, with output to show what was updated. For example:
```
$ circup update --all
Found device at /media/ntoll/CIRCUITPY, running CircuitPython 4.1.0.
Found 7 module[s] needing update.
Updated adafruit_ntp
Updated adafruit_pyportal
Updated adafruit_ssd1306
Updated adafruit_st7789
Updated adafruit_apds9960
Updated adafruit_esp32spi
Updated adafruit_rgb_display
```
In terms of code, this is a pretty trivial change. No tests added since this is IO based stuff provided by the `click` module.
=> Add --all flag to update command.

CHANGES.rst, MANIFEST.in, circup.py
As noted in #17, `setup.py` fails when installing from PyPI because `CHANGES.rst` is not distributed. This adds a `MANIFEST.in` file, which should force the file to be distributed.
Note: after merge, use tag `0.0.3` when releasing to match this with the version that will be annotated in PyPI.
=> Add CHANGES.rst To PyPI Manifest

circup.py, tests/test_circup.py
Fixes #20.
This PR introduces two changes:
* If an HTTP error code is encountered when updating the bundle release, then log the error, print a friendly error message and sys.exit 1 (error).
* Tests for the above.
Thanks to @makermelissa for reporting this problem. :+1:
=> Handle HTTP Error codes when ensuring bundle update.

README.rst, circup.py
This adds support for managing project module requirements through a requirements.txt file. The freeze command can now output a requirements.txt file for all modules installed on a connected device. The install command can then use the requirements.txt file to install a list of requirements to a connected device.
The expected workflow would be that a project could export a requirements.txt file with the modules required for their project and provide the file in the project source. Another user could then quickly install all of the required modules for the project onto their device.
This is built on top of the existing install command which does not consider module versions. For later I think as there would need to be a way to organize all of the module versions.
Close #29
=> Add requirement.txt support for freeze and install commands

requirements.txt, setup.py
* This PR fixes #39 (no known package of `Click` for Python3.9).
* I've allowed the latest version of `Click`(rather than a pinned version) to be installed.
* This is a quick fix and I don't currently have any devices to hand in order to test this change (sorry).
* Before merging please `pip install .` in a Python3.9 virtualenv and try the command out to ensure the bump in version for the package `Click` doesn't break anything.
Of course, given the quick nature of this PR please don't hesitate to discard it.
=> Bump version of click in package dependencies.

circup.py
This creates the `/lib` folder if it does not exist when installing a library on the device
=> create the lib folder if it does not exist on the device

circup.py, setup.py
This is to fix the versioning not being automated.
These changes bring the `setup.py` and `library_name.py` in other Adafruit library repos. See https://github.com/adafruit/Adafruit_CircuitPython_Requests). 
I can install the local version `pip install . and it works, but that doesn't get versioned.
I'm not sure how to test that locally, so I'm going to mark it as a draft and ask for feedback on Discord.
=> Update setup and add automated semver

.vscode/settings.json, circup.py
This fixes #48 
Click has builtin cross python support to figure this out and we are using click's version_option, but we were passing __version__. If we don't do that, Click figures it out for us correctly.
=> Don't pass version and Click will figure it out

make.cmd
after make.py was moved to make subdirectory, make.cmd needed to be edited to add make\ to call.
=> add make\   to call to make.py

circup.py, requirements.txt, setup.py, tests/test_circup.py
Fixes #25 
This warns the user both in the list and the in update command if an update is a major version update.
This is NOT done when using update --all, which sort of makes --all a bit more like --force in other CLI tools.
The text I chose to add to the CLI help and the prompts could probably use a little tweaking.
=> Warn on major version changes

circup.py, requirements.txt, setup.py
Fixes #53 
This updates semver to the latest stable and makes the code changes to switch from semver.compare() which is soon to be deprecated. Converting the stings to VersionInfo and then comparing is straight-forward.
Local testing passed.
=> update to latest stable semver

circup.py, requirements.txt, tests/test_circup.py
I added a global --path  option to allow the user to override the circuitpython device path autodetection.
Example usage:
```
circup --path /run/media/user/CIRCUITPY1 list
```
I have only tested this change on Linux so I cannot be sure it will work on Windows or macOS. My expectation is that it should work since the full path must be specified.
Note: I had to upgrade the pluggy requirement to run pytest on python 3.8.6
=> Add --path option to support non-standard mount points or multiple devices.

circup.py
when --verbose is enabled, show the device version and bundle version during update
=> show the device and bundle versions on update when verbose is enabled

README.rst, circup.py
Fixes #65 
This was pretty straight-forward.
Using the [nargs parameter of the click.arguments](https://click.palletsprojects.com/en/7.x/arguments/?highlight=click%20argument#variadic-arguments) allows you accept more than one library and then it is just iterating over that tuple. As I was re-reviewing this to update the readme, I see the uninstall already had this. 
I tested install and uninstall with a single package and 4 packages, --verbose --py as well.
=> Fix 65 - Multi module install

circup.py
- Fixes #71 
- Moved skipping non-mcu libraries to logging, output is cleaner now
- Moved some logic into its own function `get_requirements()` which makes `get_dependencies()` a little cleaner too
I pretty quickly hit rate limiting using the GitHub API, so I am using a regex approach similar to what's described in the issue.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
"For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests."
=> retrieve default branch via regex

circup.py, tests/device.json, tests/test_circup.py
Adds a "clean_version" function that removes the v in front of the version number so semver won't choke on it. There is a related idea that does a little more in the semver documentation:
https://python-semver.readthedocs.io/en/2.13.0/usage.html#dealing-with-invalid-versions
Also changes expecting a _`ValueError` in addition to a `TypeError`_ in `Module.major_update()`, so that bad version strings are caught. This fixes crashing circup. Remaining bad version numbers are assumed to be major updates.
This PR fixes #79 in regards to the adafruit_si7021 version. But adafruit_rplidar's `0.0.1-auto.0`, from which we can't extract the real version number anyway, will simply be assumed to need updating.
=> Accept version strings with v

circup.py
fixes #81 
This uses requirements from the bundle.
Note that it only looks for requirements in the py bundle path. I don't know of a reason we should look in the MPY bundle instead of the py bundle for this information.
=>  Use requirements from the bundle 

circup.py, tests/test_circup.py
There are two `requests.get()` calls to github which are used to extract release/latest tag information and in the process download the entire page. These have been replaced with a new function `get_latest_release_from_url()` which uses `requests.head()` and the response headers parsed for a 'Location' and the tag extracted from this.
`get_latest_tag()` is potentially called often and does not store it's result. This leads to a full page download from github for every library checked. This has been replaced with a single call from `main()` and the result is stored in the global `LATEST_BUNDLE_VERSION`.
**Note:** This breaks the tests and I don't know the best way to go about fixing this. This is the reason for the Draft status.
**BEFORE:**
```
❯ rm -rf ~/.local/share/circup/
pi in …
```
=> Reduce bandwidth to github when running CircUp

readthedocs.yml
RTD has been failing
https://readthedocs.org/projects/circup/builds/13343939/
Adding this config file which matches the cookiecutter repo so RTD knows the name of the requirements file. It is defaulting to rtd_requirements.
=> Add missing read the docs config

circup.py, tests/test_circup.py
Related to #98 
I woke up this morning and remembered we need to add 7mpy directly.
This adds the 7mpy url for download and bumps the tests up by 1.
=> Add support for CP7 MPY bundles

README.rst, circup.py, tests/test_circup.py
This adds support for a list of bundles, currently hard coded as the Adafruit Circuitpython Bundle and the Community Bundle. It is a stepping stone to discuss the implementation, what the requirements are for a bundle to be usable by circup, and test it before moving forward with generic bundles support.
Accessing an external list of supported bundles would be done in `get_bundles_list()`, whether it's a file in the repository, updated from an online resource or a local list of private bundles managed by CLI commands (or all three).
- A Bundle is uniquely defined by the github repository `user/repo` string
- The Bundle class handles urls, paths and tags following the current bundles conventions
- If multiple libraries have the same name, the first one found by order of the bundles list is …
=> Support for community bundle and future bundles

README.rst, circup.py, requirements.txt, setup.py, tests/test_circup.py
This PR adds module names completion for the install command using [click's completion feature](https://click.palletsprojects.com/en/7.x/bashcomplete/).
I installed the completion using the "Activation Script" method, and it works quite well, if a little slowly.
`circup install n`+tab -> `circup install neopixel` (+tab: offers `neopixel` and `neopixel_spi` completions)
`circup install a` + tab -> `circup install adafruit_` + m a g + tab -> `circup install adafruit_magtag `
=> add module names completion for install

circup.py
This adds the CircuitPython org bundle to the list that circup will check for installing libraries.
I tested locally by running:
```
python circup.py install displayio_annotation
```
which did successfully install the annotation library on my device.
=> adding circuitpython org bundle

circup.py
added Pimoroni LTR559 library to the not_standard_names dictionary.
```
user@machine:~/repos/circup $ python3 ./circup.py --path /tmp/circuitpython show | grep ltr559
pimoroni_circuitpython_ltr559
```
```
user@machine:~/repos/circup $ python3 ./circup.py --path /tmp/circuitpython install pimoroni_circuitpython_ltr559
Found device at /tmp/circuitpython, running CircuitPython 6.3.0.
Searching for dependencies for: ['pimoroni_circuitpython_ltr559']
WARNING:
pimoroni_ltr559 is not a known CircuitPython library.
Ready to install: []
```
Post addition:
```
user@machine:~/repos/circup $ python3 ./circup.py --path /tmp/circuitpython install pimoroni_circuitpython_ltr559
Found device at /tmp/circuitpython, running CircuitPython 6.3.0.
Searching for dependencies for: …
```
=> fix Pimoroni LTR559 is not a known CircuitPython library

circup.py, tests/test_circup.py
If there is an update to CP available, display the URL to circuitpython.org, using the Board ID if available.
Note that until 7.0.0 reaches stable, the "latest" is still 6.3.0, so to test you have to downgrade to an earlier version (which won't include the Board ID).
```py
Found device at /Volumes/CIRCUITPY, running CircuitPython 6.2.0.
A newer version of CircuitPython (6.3.0) is available.
Get it here: https://circuitpython.org/downloads
```
Or use a boot_out.txt from the latest build with a fake version number.
```py
Found device at /Volumes/CIRCUITPY, running CircuitPython 6.2.0.
A newer version of CircuitPython (6.3.0) is available.
Get it here: https://circuitpython.org/board/raspberry_pi_pico
```
A few small things coming with it too:
- Silence pylint's new(?) …
=> Display the URL to update Circuitpython

circup/__init__.py, tests/test_bundle_config_local.json, tests/test_bundle_config_local.json.license, tests/test_circup.py
This adds commands to manage a local list of 3rd-party bundles.
- `bundle-show` lists (all) the bundles. `--modules` lists the modules for each bundle.
- `bundle-add "user/repo"` adds a bundle from the repository at `https://github/user/repo`. It does some level of checking that the repo exists, has a release, and the zips URLs exist. It doesn't check the content of the zips at this stage.
- `bundle-remove "user/repo"` removes a bundle from the local list. `--reset` removes them all.
- The repository URL is a valid bundle reference too.
The list is separate from the built-in bundles, which can not be removed via the commands. In case of module names clashing, local bundles have priority over the built-in ones, and are checked in the order they were added. Finer management of priorities …
=> Add commands for a local list of 3rd party bundles

.github/workflows/build.yml, .gitignore, circup/__init__.py, tests/test_circup.py
Remove 6.x from platforms so that circup will not download these bundles any more.
Resolves: #131 
Tested successfully locally by running this in the repo
```
pip install .
```
and then installing a library with:
```
circup install adafruit_io
```
=> remove 6.x platforms

circup/__init__.py, requirements.txt, setup.py
Uses `update-checker` to determine if a newer version of circup is available. Will print a message like:
```
Version 1.0.2 of circup is outdated. Version 1.0.3 was released 6 days ago.
```
Tested by hand by code modification.
Determining `circup`'s own version is not so easy. `__version__` is not correct.  Code taken from how click does it.
Q: is `requirements.txt` used at all? Should it be removed?
Fixes #135.
=> Report if a newer version of circup is available

circup/__init__.py
- Fixes #141.
Add `circuitpython_typing` to the `NOT_MCU_LIBRARIES` list. Reorder the library canonicalization flow to do the `NOT_MCU_LIBRARIES` check earlier, to avoid mangling the incoming name to soon. Improve variables names in that flow.
Note that `circup` now checks for new versions, so users should get notified this is available when it is released.
=> special-case circuitpython_typing

circup/__init__.py
Some libraries (currently 3) now show up with this:
```py
__version__: str = "1.0.13"
__repo__: str = "https://github.com/adafruit/Adafruit_CircuitPython_AHTx0.git"
```
Circup couldn't read those, this updates the RE to skip type annotations (it's always `str` but I made it `\w`)
Before:
```
❯ circup list
...
Module          Version  Latest   Update Reason  
--------------- -------- -------- -------------- 
adafruit_ahtx0  1.0.12   unknown  Major Version  
adafruit_ticks  1.0.3    1.0.4    Minor Version  
```
After:
```
❯ circup list
...
Module          Version  Latest  Update Reason  
--------------- -------- ------- -------------- 
adafruit_ahtx0  1.0.12   1.0.13  Minor Version  
adafruit_ticks  1.0.3    1.0.4   Minor Version 
```
=> fix reading __version__ and __repo__ with type annotations

circup/__init__.py
Same fix for the filter of pip requirements as in circuitpython-build-tools:
Add `~[;` to filter requirements and strip() spaces. [See here examples of valid formats](https://pip.pypa.io/en/stable/reference/requirement-specifiers/#examples).
Example offending library, `~` in the last line of: https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/d24b8325f23cc933eb1df42c37aa4bc5a8387fe2/requirements.txt#L9
=> fix filtering all pip version strings in requirements.txt

circup/__init__.py
This avoids crashing into an exception when an mpy file is not found to be valid. That happens when it doesn't start with the expected headers (M3 or C5). This can happen if the file is corrupted, empty, or for example a py file is renamed mpy.
The version is set to a special value, and a warning is emitted during update similarly to when the format is valid but does not match the version of Circuitpython.
I didn't add a unit test yet.
fixes #146
=> Fix crash when bad MPY file

circup/__init__.py
When circup looks at the board libraries it reads them all to find the version number and incompatible or invalid MPY files.
But it only looked at the first level files. This PR makes it look at all levels using the `**/` pattern and recursive glob option.
At least one library, `adafruit_displayio_layout` has no file at the first level that contain version information (only an empty init).
before
```
❯ circup freeze
Found device at /Volumes/CIRCUITPY, running CircuitPython 8.0.0-beta.6-62-g7522522a0-dirty.
adafruit_displayio_layout==None
```
after
```
❯ circup freeze
Found device at /Volumes/CIRCUITPY, running CircuitPython 8.0.0-beta.6-62-g7522522a0-dirty.
adafruit_displayio_layout==1.19.10
```
=> Find all files in packages

.pre-commit-config.yaml, circup/__init__.py, tests/bad_python.py, tests/test_circup.py
- The install `--auto-file` option now implies `--auto`, so we don't have to put both.
- Auto file accepts absolute paths (like what you get when drag-and-dropping the file to the terminal).
- Auto file takes local relative paths starting with "./" (might not work on windows ⚠️).
- If the analyzed file has an error, it's caught and circup stops with a message instead of a stacktrace.
For example with this `test.py`:
```py
if True:
```
```
❯ circup install --auto-file /Volumes/CIRCUITPY/test.py 
Found device at /Volumes/CIRCUITPY, running CircuitPython 8.0.0-beta.6-62-g7522522a0-dirty.
Unable to read the auto file: "expected an indented block (test.py, line 1)"
```
Note: adds a bad python file for tests, which also has to be ignored in pre-commit.
=> Auto install improvements

circup/__init__.py
Dunno how that slipped in through my tests, but I broke --auto:
```
❯ circup install --auto
...
Error: Option '--auto' requires an argument.
```
=> Fix auto requiring an argument

circup/__init__.py
Circup currently fails to install asyncio where this is referenced in
requirements.txt as adafruit-circuitpython-asyncio. This PR adds the 
asyncio module to the "non-standard library" list
=> correctly install asyncio from requirements.txt

circup/__init__.py, tests/test_circup.py
Remove trying to install from 7.x bundle. The 2023-10-03 7.x bundle was the last one.
=> 7.x bundles are no longer built

circup/__init__.py
``I added two more parameters to circup to override board_id a CPY_VERSION detection.
The motivation is the ability to manage the version of libraries in local projects on the computer's filesystem.
I maintain several dozen CircuitPython projects, and with these parameters I can easily keep all the project's libs up to date without having to keep uploading them to the development boards.
Without these parameters, it is necessary to add a boot_out.txt file to the projects to emulate the board. With these parameters, management is much more convenient.
Example:
`circup --path d:\cpy\picopad\demo1 --board-id pajenicko_picopad  --cpy-version 8.2.6 list`
Help message:
```
circup  --help
Usage: circup [OPTIONS] COMMAND [ARGS]...
A tool to manage and update libraries on a CircuitPython device. …
```
=> Add board-id and cpy-version params

circup/__init__.py, tests/test_circup.py
- Add `9.x-mpy` platform.
- Print out platform designator when downloading, e.g., `py`, `8.x-mpy`, `9.x-mpy`.
- Print "Extracting:" in front of progress bar to make it clear that's unzipping, not downloading.
- Don't give up and exit if the particular bundle can't be downloaded. Use an existing one if possible. Otherwise, circup becomes unusable when there is a missing bundle or other problem. This was motivated by the latest bundles not being built properly (due to Python 3.12 becoming available as Python 3.x in GitHub CI), causing circup to stop working.
Example of new output. The platform designators have to be on a line of their own due to when exceptions are thrown and how the progress bar works.
```
$ circup install neopixel
Found device at /media/halbert/CIRCUITPY, running …
```
=> add 9.x-support; don't give up if download fails

requirements.txt, setup.py
Updates requirements.txt and setup.py to reference semver for the next major release, 3.0.0
There are no code changes needed to support this as circup doesn't use any of the deprecated
features, or so it seems.  The biggest change here from what I can tell is that python 2 is no longer supported.
pytest results:
```
=================================================================================== test session starts ===================================================================================
platform linux -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/james/Projects/imnotjames/circup
plugins: hypothesis-6.88.1
collected 50 items …
```
=> chore: bump semver to 3.0.x

circup/__init__.py
This change makes circup look for a circup section with circup_dependencies inside of the pyproject.toml file and use it as an additional list of dependencies that is separate from requirements.txt. This is to be used for circuitpython libraries that are included in bundle, but not deployed to pypi and thus aren't valid in requirements.txt
Here is an example declaration of one such dependency this was tested with:
```
[circup]
circup_dependencies = ["cedargrove_midi_tools"]
```
=> Add support for Pyproject toml circup dependencies

setup.py
resolves #191
Tested in an empty venv and with this change I'm able to use circup immediately after installing.
=> add toml to dependency list

circup/__init__.py
- **Describe the scope of your change--i.e. what the change does and what parts
of the code were modified.**
This change fixes a bug with the code following a change to the `semver` package which renames the `isvalid()` method to `is_valid()`. Fixes https://github.com/adafruit/circup/issues/193
- **Describe any known limitations with your change.**
n/a
- **Please run any tests or examples that can exercise your modified code.**
n/a
=> Fix renamed `is_valid()` method call

.github/workflows/build.yml, .github/workflows/release.yml, circup/__init__.py, tests/test_circup.py
Fixes #165.
Fixes #196.
- Handle .mpy files with bytecode version `C\x06`. The `__version__` string is not findable in as straightforward a way because the way dictionary entries are in the .mpy has changed, so just look for the first string that looks like a version number.
Tested on 8.2.9 and 9.0.0-beta.0, including upgrading and downgrading between those versions.
=> Handle mpy version checking for Circuitpython 9

circup/backends.py
This change adds check for web API version on the device to make sure the web workflow backend can actually work.
=> refuse any device with web API version stricly less than 4

README.rst, circup/backends.py, circup/bundle.py, circup/command_utils.py, circup/commands.py
This change adds a new subcommand `circup example` which can be used to copy examples from the bundle onto the device. 
example:
```
$ circup example bme680/bme680_simpletest
$ circup example bme680/bme680_simpletest bme680/bme680_spi --overwrite
```
The name of the file is kept. If a file by this name exists on the device already a warning is printed that the file exists. User can pass `--overwrite` to replace the file even if it exists.
The command supports tab completion that tries to find matching library name / example name strings based on the partial argument entered by the user. 
`_install_module_py` and `_install_module_mpy` were refactored to become non-private (drop the leading underscore). The example command makes use of the py version of that function from outside of the …
=> Example command

circup/backends.py, circup/commands.py
resolves #209 
Adds `--upgrade` as an option for `circup install` which behaves effectively the same as pip. If this flag is passed it will remove any modules found to be installed already before installing the latest one from the bundle. If the flag is omitted the default behavior is same as today which is print out a message but do not overwrite the existing one.
=> Upgrade flag

circup/backends.py, circup/command_utils.py, circup/commands.py
This allows local filepaths to be passed to `circup install` instead of libraries that exist in a bundle. 
So it becomes possible to do something like:
```
circup install synth_tools
```
which will install the local module at the directory `synth_tools/` if it exists (or print an error if not).
That makes  it so that circup can be used to install libraries that are not in any bundle but still shared in git repositories or other ways.
@todbot was one person interested in this functionality. If you have the opportunity to test this it's much appreciated.
=> Support Local Path Install

circup/commands.py
This adds support for an optional environment variable `CIRCUP_WEBWORKFLOW_PASSWORD` if set it's value will be used if the `--password` argument is omitted allowing the command to succeed if the variable contains the correct password.
e.g.
```
export CIRCUP_WEBWORKFLOW_PASSWORD="yourpassword"
circup --host 192.168.1.188 install adafruit_display_shapes
```
Help output for `--password` is updated to mention this new env variable.
This allows you to type less if you are manually entering commands as well as hide your password if you are streaming or using some other screenshare (if you export the variable off screen).
=> env var CIRCUP_WEBWORKFLOW_PASSWORD

circup/backends.py, circup/commands.py
resolves #218 
If `--cpy-version` CLI argument is passed by user, then pass it's value to the Backend constructor and store it in a local variable to be returned if it exists from `get_circuitpython_version()` 
I was able to successfully test this version with these commands:
```
circup --path fake_project/ --cpy-version 8.0.0 --board-id hello install adafruit_display_text
circup --path fake_project/ --cpy-version 9.0.0 --board-id hello install adafruit_display_text
```
=> fix version overriding arg

.github/workflows/release.yml
This is the same as here: https://github.com/adafruit/workflows-circuitpython-libs/blob/main/release-pypi/action.yml#L39 which is one of the files that the new release.yml is modeled after, I ended up changing most of the code over to a different one from circuitpython-build-tools, but in the process I mistakenly removed this install which now made the new release fail.
=> add build for release

pyproject.toml
This seems to resolve the issue of pip not installing the dependencies correctly when you do `pip install circup` 
I tested it successfully with `pip install .` and it will need re-testing with the real name once deployed.
=> enable dynamic depencies

circup/commands.py
Implementation of feature request #140, this is something I would really like to see as a PyCharm user. 
As described in the [PyCharm + CircuitPython setup guide](https://learn.adafruit.com/welcome-to-circuitpython/pycharm-and-circuitpython) there are packages available on PyPi that contain stubs for libraries from the Adafruit Library Bundle, these packages help give the IDE you are using context for your CircuitPython code so that code hinting can work properly.
Instead of having to manually install these stubs after installing packages using CircUp, this PR adds the `--stubs` flag to the `circup install` command which enables a step in the installation process to try to install the available stubs package using `pip`.
This would currently only work for libraries in the Adafruit …
=> Adding option to install library stubs from PyPi

circup/backends.py, circup/command_utils.py, circup/commands.py
The web workflow can run on an alternate port number; I set one of my devices up this way and then noticed I couldn't use it with circup.
```
CIRCUITPY_WEB_API_PORT=8080
```
With this change, I can specify `--port 8080` and successfully install libraries.
=> Support web workflow on alternate port numbers

.pre-commit-config.yaml, .pylintrc, circup/shared.py
The two changes with this PR allow circup to be used under python 3.12 in the following contexts:
- `circup` CLI usage by the user
- pre-commit usage by developers working on circup.
=> python 3.12 support

circup/shared.py, docs/conf.py
There is an issue when reading the version number in `adafruit_httpserver` because [one of the files contains the string](https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/blob/bcef270a3dcb6a4ba34a2fb4f12a972142a1390d/adafruit_httpserver/server.py#L237) `"0.0.0.0"`. Twice. (A default argument for an IP address). So the version number ends up being `0.0.0`.
```
adafruit_httpserver     0.0.0    4.5.10  Major Version
```
So as a tentative solution to situations like that, I made two changes:
- sort the files scanned by name, so that the `__init__.mpy` file is read first.
- keep the first version number found instead of updating to the last.
I believe that the version number will be the first version-like string in the file, since strings in MPY files seem to be in the same order …
=> Slight improvement to reading MPY files module version

circup/backends.py, circup/commands.py, circup/wwshell/commands.py
After https://github.com/adafruit/circup/pull/223 was merged the actions did not pass. This PR is trying to fix the issues that caused it to fail.
The port argument was missing in some of the function calls. I must have been using a version with the default port hardcoded back when I worked on this before. 
The other pylint error was for duplicate lines between wwshell.main and circup.main. I looked for ways to refactor the initial section but didn't come to any implementation that wasn't more complex. The fact that this chunk sets a few local variables coupled with the fact that circup actually has an else block for when not using_webworkflow make it tricky to try to refactor this into a shared function. 
Also removed a handful of print statements.
=> wwshell fixes

circup/backends.py, circup/command_utils.py, circup/commands.py
This PR adds the --list and --rename options to the circup example command.
Example now includes an option --list which will allow searching for examples.
Examples are:
circup example --list requests
would return all the valid example file or directories contained in the requests library.
circup example --list disp
returns all the libraries and examples that match disp*
circup example --list
would return a list of all the libraries with examples
On copy if the named example resolves to a single file and the new --rename option is added then the output to the device is named code.py in keeping with the CricuitPython runtime.
This change also caches the example library metadataa which speeds up the tab completion and the --list options.  Previous to this change there was quite a noticeable …
=> Add --list and --rename options to circup example command

.github/workflows/build.yml, circup/shared.py, tests/mock_device/boot_out.txt, tests/test_circup.py
As discussed in the weekly CircuitPython meeting, https://github.com/adafruit/adafruit-circuitpython-weekly-meeting/blob/main/2025/2025-02-03.md#2643-in-the-weeds, we will drop building 8.x bundles. 
- This is on the checklist here: https://github.com/adafruit/circuitpython/issues/9001
@FoamyGuy I think the tests mostly don't need to change, because the testing is with mocked versions. I'll see if the tests pass!
=> drop 8.x bundle support

circup/config/bundle_config.json
The circuitpython org bundle isn't built for mpy 10.x so it outputs an error message when circup attempts to download it. 
This removes circuitpython org bundle. Those libraries will get migrated into the community bundle and it should require no further changes to circup to use them once that is complete.
=> remove circuitpython_org bundle

circup/command_utils.py, tests/mock_device/apps/test_app/import_styles.py, tests/mock_device/apps/test_app/import_styles_sub.py, tests/mock_device/boot_out.txt, tests/mock_device/import_styles.py, tests/mock_device_2/boot_out.txt, tests/mock_device_2/import_styles_sub.py, tests/test_circup.py
resolves #252.
In order for `get_all_imports()` to be able to recursively find subimports it must know where the original file is located instead of just the content of that file. Otherwise it won't be able to find files that are stored alongside `code.py` in directores that are outside of the root such as the ones used by Fruit Jam OS like: `apps/something/` 
This change adds the filepath as an argument and uses it to locate the imported files. Theoretically we could remove the file content arg and read the file inside of the function if we wanted one fewer arguments. I left it as is for now though and do not have a strong preference one way or the other in this case.
=> fix subimport finding for auto-files that are not in the root.
